title: The raindrops tapping the window I sat by
author:
  name: Hui
  email: gewachs@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  My thoughts, journals and books

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer

  social_links:
    - { platform: twitter,        user_url: "https://twitter.com/ybananacurve" }


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima


header_pages:
  - archive.md
#  - books.md
  - SwedishLearning_Ove.md
  - thoughts.md

gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html

# Explicitly turn off the old code
paginate: nil
paginate_path: nil

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  offset: 2
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
